export const DEFAULT_SKIN_ID = "teal-squire";

export const rarityMeta = {
  common: { label: "普通", tone: "#37a092" },
  uncommon: { label: "精良", tone: "#4d8fd7" },
  rare: { label: "稀有", tone: "#8c70d9" },
  epic: { label: "史诗", tone: "#d076a6" },
  legendary: { label: "传说", tone: "#d59a28" },
};

export const skins = [
  {
    id: "teal-squire",
    name: "青岚见习者",
    title: "默认皮肤",
    rarity: "common",
    price: 0,
    image: "/skins/teal-squire.png",
    accent: "#2aa99b",
  },
  {
    id: "moon-cloak",
    name: "月影披风",
    title: "夜巡者",
    rarity: "uncommon",
    price: 80,
    image: "/skins/moon-cloak.png",
    accent: "#4a6fae",
  },
  {
    id: "academy-mage",
    name: "学院术士",
    title: "书页使者",
    rarity: "uncommon",
    price: 120,
    image: "/skins/academy-mage.png",
    accent: "#315f9f",
  },
  {
    id: "lamp-wanderer",
    name: "提灯旅人",
    title: "晚风向导",
    rarity: "uncommon",
    price: 140,
    image: "/skins/lamp-wanderer.png",
    accent: "#d09a3f",
  },
  {
    id: "starter-blade",
    name: "初心剑士",
    title: "任务开拓者",
    rarity: "common",
    price: 60,
    image: "/skins/starter-blade.png",
    accent: "#257f7b",
  },
  {
    id: "shadow-scroll",
    name: "黑卷密探",
    title: "暗线记录员",
    rarity: "rare",
    price: 220,
    image: "/skins/shadow-scroll.png",
    accent: "#303744",
  },
  {
    id: "arcane-scholar",
    name: "奥术学者",
    title: "专注法典",
    rarity: "rare",
    price: 260,
    image: "/skins/arcane-scholar.png",
    accent: "#2a67b1",
  },
  {
    id: "desert-guide",
    name: "沙原向导",
    title: "绿洲搜寻者",
    rarity: "uncommon",
    price: 150,
    image: "/skins/desert-guide.png",
    accent: "#2b887b",
  },
  {
    id: "time-apprentice",
    name: "时钟学徒",
    title: "时间齿轮",
    rarity: "rare",
    price: 280,
    image: "/skins/time-apprentice.png",
    accent: "#1d91b7",
  },
  {
    id: "focus-oracle",
    name: "专注先知",
    title: "蓝晶凝视",
    rarity: "epic",
    price: 420,
    image: "/skins/focus-oracle.png",
    accent: "#00a8de",
  },
  {
    id: "star-alchemist",
    name: "星砂炼金师",
    title: "星图记录",
    rarity: "epic",
    price: 460,
    image: "/skins/star-alchemist.png",
    accent: "#544cd0",
  },
  {
    id: "clockwork-runner",
    name: "发条行者",
    title: "计时游侠",
    rarity: "rare",
    price: 300,
    image: "/skins/clockwork-runner.png",
    accent: "#2a9db9",
  },
  {
    id: "iron-vanguard",
    name: "铁誓先锋",
    title: "盾墙守卫",
    rarity: "rare",
    price: 320,
    image: "/skins/iron-vanguard.png",
    accent: "#536a7d",
  },
  {
    id: "ember-rogue",
    name: "余烬游侠",
    title: "燃刃行踪",
    rarity: "epic",
    price: 500,
    image: "/skins/ember-rogue.png",
    accent: "#d75b27",
  },
  {
    id: "frost-guard",
    name: "霜晶守卫",
    title: "雪原契约",
    rarity: "epic",
    price: 520,
    image: "/skins/frost-guard.png",
    accent: "#55aee4",
  },
  {
    id: "storm-lancer",
    name: "雷霆枪骑",
    title: "云端突击",
    rarity: "rare",
    price: 340,
    image: "/skins/storm-lancer.png",
    accent: "#4068c8",
  },
  {
    id: "spring-ranger",
    name: "春森巡林者",
    title: "新芽弓手",
    rarity: "rare",
    price: 300,
    image: "/skins/spring-ranger.png",
    accent: "#54a767",
  },
  {
    id: "summer-scout",
    name: "夏日轻装",
    title: "晴风小队",
    rarity: "common",
    price: 90,
    image: "/skins/summer-scout.png",
    accent: "#3aa98d",
  },
  {
    id: "autumn-bard",
    name: "秋叶吟游",
    title: "金叶乐章",
    rarity: "rare",
    price: 330,
    image: "/skins/autumn-bard.png",
    accent: "#c4822b",
  },
  {
    id: "winter-mystic",
    name: "冬夜秘术师",
    title: "星霜咏者",
    rarity: "epic",
    price: 560,
    image: "/skins/winter-mystic.png",
    accent: "#6d62d6",
  },
  {
    id: "royal-hero",
    name: "王庭勇者",
    title: "荣光之证",
    rarity: "legendary",
    price: 760,
    image: "/skins/royal-hero.png",
    accent: "#d6a033",
  },
  {
    id: "void-knight",
    name: "虚空骑士",
    title: "暗星战甲",
    rarity: "legendary",
    price: 880,
    image: "/skins/void-knight.png",
    accent: "#7258de",
  },
  {
    id: "dream-collector",
    name: "梦境收藏家",
    title: "月相契约",
    rarity: "epic",
    price: 580,
    image: "/skins/dream-collector.png",
    accent: "#7866e8",
  },
  {
    id: "golden-sage",
    name: "金辉贤者",
    title: "终章观测",
    rarity: "legendary",
    price: 980,
    image: "/skins/golden-sage.png",
    accent: "#d99a2b",
  },
];

export const skinMap = new Map(skins.map((skin) => [skin.id, skin]));

export function getSkin(id) {
  return skinMap.get(id) || skinMap.get(DEFAULT_SKIN_ID);
}
